### ISSUE TITLE
I tried to use your setup on my server to use Flash speedtest.net by Ookla but it doesn't work :(

### ISSUE THREAD

**Issue by Galateanul** [veso266/Flash-Speedtest.net-by-Ookla#1]
Hi! I came across this interesting publication because I was by now searching resignedly for a guide on how to use the flash version of the speedtest.net site.
I read everything and downloading the files I found the folder "MySetup" where there was a file to read and all the files that I had to upload to the server in order to use it.
I modified the file as you wrote but as soon as I open the site it tells me "Wrong Licence"...
Could you help me to solve this problem? I think you are the last hope to be able to use the old speedtest

**Comment by veso266** [comment]
Hi there

You need to use a keygen (Keygen folder, pick the language you want), to generate yourself the license)

If you use Javascript one just open Keygen/javascript/index.html, then open your javascript console and write
```js
console.log(GenerateKey("3/19/2025 08:00:00 GMT", "YourHostname(url your hosting speedtest on", 11, 
"Bound2Domain", "domain-you-host-your-speedteston-can-be-localhost", speedtest", "new"));

And copy your key into mySetup/config.xml
<LicenseKey>

That should solve the license problem (you can also open debug menu by clicmking on your speedtest screen and writing debug (a console like menu should open telling you if you are secsesfull)

As for the servers, there are still some left here: https://speedtest.net/speedtest-servers.php you can try

And you can always host your own one if you want (will send you files if you want them)


Hope you make it work, if not just ask again and will help you

**Comment by Galateanul** [comment]
Hi! Unfortunately, it didn't work...
I explain better what I did: I opened the javascript file with Google Chrome then I opened the console and entered the command you gave me. I was given the code which I then pasted on config.xml at line 4 where it says <licensekey>.
Once this was done I uploaded all the files to infinityfree where I host the site and it still gives me "Wrong License" when I open it.
I tried to generate a new license but I notice that the code is identical.
Then I have a question: in the file to read you wrote that you have to replace speedtest.windows.nt with <server-ip-here>.
I did the procedure writing just <server-ip-here>.... Were you referring to the ip of the server that hosts the site?
I apologize but I am not very experienced :(

**Comment by veso266** [comment]
Hi there, what you need to do is figure out why your license is not correct, so for this you need to click on the flash movie, and write ``debug`` on your keyboard (just write it, nothing will show up when you write it) and some fancy console like window, will open like this
![slika](https://user-images.githubusercontent.com/6347325/147564964-d5555c65-9b55-4f7a-9488-17acc25aaf79.png)

or if your license is missing like this
![slika](https://user-images.githubusercontent.com/6347325/147565071-3177cc6b-09af-4101-a4ff-e5ba29701982.png)

or if your license is corupted it will show like this
![slika](https://user-images.githubusercontent.com/6347325/147565175-d2c94f9a-10f5-4403-a406-f263ba2981dc.png)

or if your license is wrong completly like this
![slika](https://user-images.githubusercontent.com/6347325/147565429-a969b9c9-c1e8-4110-91ce-0bd9b751fb6f.png)

you have to scroll up on the debug window a bit to see that

if you want you can send me your key your made (or I can make a key for you)(and the exact hostname you are hosting this on) and I will send you a working files for your setup

Happy holidays

**Comment by Galateanul** [comment]
MySQL Hostname: sql200.epizy.com
FTP Hostname: ftpupload.net
WEBSITE LINK: speedtestnet.42web.io
Website IP: 185.27.134.118
This is what I found on my Infinityfree page where I'm hosting all the setup.
It would be really great if you could generate a working key, I really appreciate the support!
Yes I was the user who wrote the question. For the Flash Player I use an old version of chrome that I have prevented updates to. It works very well. 
![Screenshot (36)](https://user-images.githubusercontent.com/96704065/147674495-598b142c-843f-42a5-8dc0-01374e71eabf.png)
This is the file menager that allows me to upload file for the site.
![Screenshot (38)](https://user-images.githubusercontent.com/96704065/147674842-1bafa9bd-79d9-4d98-9426-100e33f7623a.png)
Where you told me to put <server-ip-here> I put the ip of the site. Is that correct?

**Comment by Galateanul** [comment]
![Screenshot (41)](https://user-images.githubusercontent.com/96704065/147775539-8d51a020-4fce-46a0-8d71-8f0424a7af31.png)
![Screenshot (42)](https://user-images.githubusercontent.com/96704065/147775546-8fb9ddcf-486c-49ae-825d-4b113d459a2b.png)
I forgot...this is my debug window

**Comment by veso266** [comment]
![slika](https://user-images.githubusercontent.com/6347325/147777551-449dfcea-2918-4ace-a4be-a703531f92ac.png)

Here ya go: https://www.mediafire.com/file/uzvs7acsw07laam/speedtest.zip/file

as for the servers, it does work with the new servers but you'ill have to list them yourself (there is no public file of them anymore) so you have to go to new speedtest use tool like fiddler to inspect the server their client is connecting to and the manualy type it in servers.xml

I've got 2 servers for you (Telenor Speedy and Telenor Speedy 2 (which doesn't work its just  a placeholder for you to put your own server in once you create one :) but Telenor Speedy works like a charm)

Hope you like it, I know its not how it once was but its close, also the IP and ISP that is displayed is not your real one but a bogus hardcoded value you can change in config.xml under this line (I have to write a php script once that would substitute this with real info :smile:
```xml
<client ip="83.51.72.192" lat="34.0512" lon="-118.2504" isp="Telenor" isprating="2.9" rating="0" ispdlavg="9141" ispulavg="8018" loggedin="0" />
```

and some day I have to code the API (so you can generate preaty pictures of your speed again)

The license is generated for 42web.io domain, so every subdomain under 42web.io will work fine, but if you want to change the domain you have to post here again :smile:

**Comment by Galateanul** [comment]
It worked!!!! Thank you so much, you have been the saving grace. I know it's not the same as before but with a little patience I'll be able to fix it properly. Even so it manages to beat the current version that of graphics is really poor. Thanks for your patience and help I think you are the only one in the world who has done something like this :)
Happy new year and holidays!

**Comment by veso266** [comment]
That's great, please tell me when you fix it :smile:

you can even use files here: https://github.com/veso266/Flash-Speedtest.net-by-Ookla/tree/master/The%20last%20website/speedtest/c.speedtest.net

I am just happy that I am not the onlyone in the world that wants to still use old speedtest, now the onlything left to do is to rewrite the API once and make it work without flash 

to make it look even more authentic
